# Generated by Django 5.2.16 on 2026-07-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_subject_subjectmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmarks',
            name='marks',
            field=models.IntegerField(default=50),
        ),
    ]
