# Generated by Django 5.2.16 on 2026-07-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0007_alter_subjectmarks_student_reportcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='date_of_reportcard_generation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
