# Generated by Django 5.2.16 on 2026-07-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0008_alter_reportcard_date_of_reportcard_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
